#!/bin/bash
#PBS -A ERDCV00898R40
#PBS -l walltime=00:20:00
#PBS -l select=1:ncpus=32:mpiprocs=1
#PBS -q standard
#PBS -N marin
#PBS -j oe
#PBS -l application=proteus
#PBS -V
#PBS -m eba
#PBS -M aron@ahmadia.net 
source /opt/modules/default/etc/modules.sh
source /lustre/shared/projects/proteus/garnet.gnu.sh
cd $PBS_O_WORKDIR
mkdir $WORKDIR/marin.$PBS_JOBID
aprun -n 1 python code/convert_mat.py 4 systems/marin/marin*_L_*
