#!/bin/bash
#PBS -A ERDCV00898R40
#PBS -l walltime=00:15:00
#PBS -l select=64:ncpus=32:mpiprocs=16
#PBS -q standard
#PBS -N marin
#PBS -j oe
#PBS -l application=proteus
#PBS -V
#PBS -m eba
#PBS -M aron@ahmadia.net 
source /opt/modules/default/etc/modules.sh
source /lustre/shared/projects/proteus/garnet.gnu.sh
cd $PBS_O_WORKDIR
aprun -n 1024 python code/test_mat.py systems/marin/marin_twp_navier_stokes_p_L*  -options_file solvers/fieldsplit_3D_asm.options
